In [1]:
import tensorflow as tf
tf.set_random_seed(777) 

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  62547.29 
Prediction:
 [-75.96345  -78.27629  -83.83015  -90.80436  -56.976482]
10 Cost:  14.468626 
Prediction:
 [145.26407 187.59541 178.152   194.48586 145.81136]
20 Cost:  13.822504 
Prediction:
 [145.9478  188.39003 178.94907 195.3521  146.41212]
30 Cost:  13.749193 
Prediction:
 [145.96422 188.38263 178.95592 195.35777 146.4012 ]
40 Cost:  13.67629 
Prediction:
 [145.97856 188.3728  178.96031 195.36082 146.38844]
50 Cost:  13.603815 
Prediction:
 [145.99286 188.36302 178.9647  195.36386 146.37572]
60 Cost:  13.531695 
Prediction:
 [146.00711 188.35324 178.9691  195.3669  146.36302]
70 Cost:  13.459941 
Prediction:
 [146.02135 188.34352 178.9735  195.36995 146.35036]
80 Cost:  13.388664 
Prediction:
 [146.03552 188.33382 178.97784 195.37292 146.33774]
90 Cost:  13.317709 
Prediction:
 [146.04967 188.32413 178.98221 195.37595 146.32515]
100 Cost:  13.247167 
Prediction:
 [146.06377 188.31447 178.98654 195.37894 146.31259]
110 Cost:  13.176931 
Prediction:
 [146.07785 188.3

1060 Cost:  7.979327 
Prediction:
 [147.25537 187.49893 179.35333 195.63098 145.25363]
1070 Cost:  7.937616 
Prediction:
 [147.26624 187.49152 179.35669 195.63327 145.244  ]
1080 Cost:  7.8960905 
Prediction:
 [147.27707 187.48409 179.36002 195.63553 145.23439]
1090 Cost:  7.8548036 
Prediction:
 [147.28787 187.47668 179.36334 195.6378  145.22481]
1100 Cost:  7.8137703 
Prediction:
 [147.29865 187.46933 179.36667 195.64008 145.21526]
1110 Cost:  7.772931 
Prediction:
 [147.30939 187.46198 179.36998 195.64233 145.20572]
1120 Cost:  7.7323503 
Prediction:
 [147.3201  187.45465 179.37329 195.64458 145.19623]
1130 Cost:  7.6919413 
Prediction:
 [147.33078 187.44733 179.37657 195.64684 145.18674]
1140 Cost:  7.651777 
Prediction:
 [147.34145 187.44005 179.37985 195.64906 145.17729]
1150 Cost:  7.611787 
Prediction:
 [147.35208 187.43275 179.38312 195.65129 145.16786]
1160 Cost:  7.5720263 
Prediction:
 [147.36269 187.42549 179.3864  195.65352 145.15846]
1170 Cost:  7.5325418 
Prediction:
 [

In [ ]:
# 이러한 방법은 matrix 를 사용하여 학습시킬 수 있다.,

In [ ]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


#placeholder 설정시 shape Node 은 값이 n개가 있을 수 있기 때문에 None
#matrix 를 사용하면 변수의 개수와는 상관 없이 간단하게 표현이 가능하다.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
