In [ ]:
#Sicing
num = range(5)
print nums  #[0, 1, 2, 3, 4] 출력
print nums[2:4] # 2를 포함해서 4 이전까지
print nums[2:] #2를 포함해서 끝까지
print nums[:] #print nums 와 동일
print nums[:-1] #처음부터 마지막 이전까지
nums[2:4] = [8, 9] # 2:4 값 즉 2,3 을 8, 9 로 Assign new sublist

In [ ]:
#출처 :https://webnautes.tistory.com/1178
import numpy as np


# 1차원 배열을 생성합니다.
A = np.arange(0, 15, 2)
print("A = ", A)
print("\n")
# A =  [ 0  2  4  6  8 10 12 14]


# 1차원 배열은 차원이 1개이기 때문에 인덱스 하나를 사용하여 NumPy배열의 원소를 접근할 수 있습니다.
print("A.ndim = ", A.ndim)
print("\n")
# A.ndim =  1


# NumPy 배열의 shape 속성으로 인덱스 범위를 확인할 수 있습니다.
print("A.shape = ", A.shape)
print("\n")
# A.shape =  (8,)   # 0 <= x < 8 이 인덱스의 범위입니다.


# 1차원 배열은 하나의 인덱스로 배열의 모든 원소를 접근할 수 있습니다.
# 배열이름[인덱스]를 사용하여 지정한 인덱스에 있는 배열의 원소를 읽어올 수 있습니다.
# 인덱스는 0부터 시작합니다.
for index, a in enumerate(A): # enumerate 함수는 배열의 원소와 인덱스를 묶어 튜플로 반환합니다. (인덱스, 배열의 원소)
    print("A[%d]=" % (index), A[index], end=", ")
print("\n")
# A[0]= 0, A[1]= 2, A[2]= 4, A[3]= 6, A[4]= 8, A[5]= 10, A[6]= 12, A[7]= 14,


# 인덱스가 음수이면 배열의 마지막 인덱스부터
 역순으로 원소를 접근하게 됩니다.
# 마지막 인덱스는 -1부터 시작합니다.
for index, a in zip(range(-1, -9, -1), A):  # zip 함수는 같은 크기의 자료형에서 하나씩 원소를 꺼내어 튜플로 리턴합니다. 
    print("A[%d]=" % (index), A[index], end=", ")
print("\n")
# A[-1]= 14, A[-2]= 12, A[-3]= 10, A[-4]= 8, A[-5]= 6, A[-6]= 4, A[-7]= 2, A[-8]= 0,


# 배열이름[i]  ->  배열의 i+1 번째 원소의 값을 읽어올 수 있습니다.
# 0부터 인덱스가 시작하기 때문에 인덱스 i로 배열의 i+1번째 원소를 읽습니다.
print("A[2]=", A[2]) # 배열 A의 3번째 원소를 읽어옵니다.
print("\n")
# A[2]= 4


# 배열이름[i]=새로운 값  -> 배열의 i+1 번째 원소의 값을 새로운 값으로 변경합니다.
A[2] = 100
print("A[2]=", A[2])
print("\n")
# A[2]= 100

#-------------------------------------------------------


# 1차원 배열을 생성합니다.
A = np.arange(0, 15, 2)
print("A = ", A)
print("\n")
# A =  [ 0  2  4  6  8 10 12 14]


print("A -> ", end=" ")
for index, a in enumerate(A):
    print("A[%d]=" % (index), A[index], end=", ")
print("\n")
# A ->  A[0]= 0, A[1]= 2, A[2]= 4, A[3]= 6, A[4]= 8, A[5]= 10, A[6]= 12, A[7]= 14,


# 슬라이싱은 다음 형태로 이루어집니다.
# 배열이름[시작 인덱스:끝 인덱스]
# 인덱스 범위는 시작 인덱스 <= index < 끝 인덱스 입니다.
# 해당 범위에 있는 원소는 다음처럼 읽어올 수 있습니다.
print("A[0:3]=", A[0:3])  # 슬라이스 A[0:3]의 원소는 A[0], A[1], A[2]으로 구성됩니다.
print("\n")
# A[0:3]= [0 2 4]


print("A[:5]=", A[:5])    # 시작 인덱스는 명시하지 않은 것이랑
print("A[0:5]=", A[0:5])  # 시작 인덱스를 명시한 거랑 똑같은 결과입니다.
print("\n")
# A[:5]= [0 2 4 6 8]
# A[0:5]= [0 2 4 6 8]


print("A[6:]=", A[6:]) # 끝 인덱스를 명시하지 않으면 마지막 인덱스도 포함되지만
print("A[6:7]=", A[6:7]) # 끝 인덱스로 마지막 인덱스를 명시해주면 포함되지 않습니다.
print("\n")
# A[6:]= [12 14]
# A[6:7]= [12]


print("A[:]=", A[:]) # 배열의 전체 원소를 포함하는 슬라이스입니다.
print("A[::2]=", A[::2]) # 첫번째 원소부터 2씩 건너띄며 원소를 취합니다. 배열의 마지막 원소까지를 대상으로 합니다.
print("A[3::2]=", A[3::2]) # 네번째 원소부터 2씩 건너띄며 원소를 취합니다. 배열의 마지막 원소까지를 대상으로 합니다.
print("\n")
# A[:]= [ 0  2  4  6  8 10 12 14]
# A[::2]= [ 0  4  8 12]
# A[3::2]= [ 6 10 14]


# 하나의 배열을 특정 인덱스를 기준으로 둘로 분리해봅니다.  
print("A[:-2]=", A[:-2]) # 마지막 두 개의 원소를 제외하고 취합니다.
print("A[-2:]=", A[-2:]) # 마지막 두 개만 취합니다.
print("\n")
# A[:-2]= [ 0  2  4  6  8 10]
# A[-2:]= [12 14]


# 슬라이스는 뷰이기 때문에 NumPy 배열과 동일한 속성을 갖습니다.
print("A[0:3].shape=", A[0:3].shape)
print("A[0:3].ndim=", A[0:3].ndim)
print("\n")
# A[0:3].shape= (3,)
# A[0:3].ndim= 1


print("변경 전 A=", A)
A[0:3]=100  # 배열의 슬라이스를 변경하면
print("슬라이스 값 변경 후 A[0:3]=", A[0:3]) #슬라이스의 모든 원소값 뿐만아니라
print("슬라이스 값 변경 후 A=", A) #원본 배열에서 해당 부분의 데이터가 변경됩니다.
print("\n")
# 변경 전 A= [ 0  2  4  6  8 10 12 14]
# 슬라이스 값 변경 후 A[0:3]= [100 100 100]
# 슬라이스 값 변경 후 A= [100 100 100   6   8  10  12  14]


# 하나의 배열에 대한 모든 슬라이스의 id는 모두 동일합니다.
# 하지만 배열 A의 id와는 다릅니다.
print("id(A)=", id(A), " ", A.size)
print("id(A[:])=", id(A[:]), " ", A[:].size)
print("id(A[0:3])=", id(A[0:3]), " ", A[0:3].size)
print("id(A[:-1])=", id(A[0:-1]), " ", A[0:-1].size)
print("\n")
# id(A)= 1471438681472   8
# id(A[:])= 1471470774912   8
# id(A[0:3])= 1471470774912   3
# id(A[:-1])= 1471470774912   7



# 인덱스로 참조한 배열의 원소의 id는 모두 동일합니다.
# 하지만 배열 A의 id와는 다릅니다.
print("id(A)=", id(A), " ", A.size)
print("id(A[0])=", id(A[0]), " ", A[0].size)
print("id(A[1])=", id(A[1]), " ", A[1].size)
print("id(A[-1])=", id(A[-1]), " ", A[-1].size)
print("\n")
# id(A)= 1471438681472   8
# id(A[0])= 1471577464000   1
# id(A[1])= 1471577464000   1
# id(A[-1])= 1471577464000   1

#----------------------------------------------------------
# 리스트를 중첩하여 2차원 배열을 생성합니다.
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("A = \n", A)
print("\n")
# A =
#  [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]


# 크기가 3 x 4인 2차원 배열입니다.
print("A.shape = ", A.shape)
print("\n")
# A.shape = (3, 4)


# 2차원 배열은 두 개의 인덱스를 사용하여 하나의 원소에 접근할 수 있습니다.
# 차원별로 인덱스는 0부터 시작합니다.
# 다음처럼 두가지 표현 방법이 있습니다.
print("A[1, 2] = ", A[1, 2])  # 두번째 행, 세번째 열의 원소의 값을 출력합니다.
print("A[1][2] = ", A[1][2])  # 위와 동일한 결과를 출력합니다.
print("\n")


# 인덱스 하나만 사용하면 하나의 행을 슬라이싱할 수 있습니다.
print("A[0]=", A[0])
print("A[0].shape=", A[0].shape)
print("\n")
# A[0]= [1 2 3 4]
# A[0].shape= (4,)


print("A[:, 1] = ", A[:, 1])   # 하나의 열을 슬라이싱 하는 방법중 한가지입니다. 전체 행( : ) 중에서 두번째 열( 1 )에 해당되는 원소들이 대상이됩니다.
print("A[:, 1].shape=", A[:, 1].shape) # 열 벡터인데도 shape가 (1,3)이 아닌 (3,) 인 것은 NumPy에서는 열벡터와 행벡터 구분이 없기 때문입니다.
print("\n")
# A[:, 1] =  [ 2  6 10]
# A[:, 1].shape= (3,)


# 배열의 일부를 슬라이싱해서 값을 변경하면 원본 배열에도 영향을 주게 됩니다.
print("변경 전 A[0:2, 0:2] = \n", A[0:2, 0:2] )
print("변경 전 A = \n", A)
print("\n")
# 변경 전 A[0:2, 0:2] =
#  [[1 2]
#  [5 6]]
# 변경 전 A =
#  [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

A[0:2, 0:2] = 0
print("변경 후 A[0:2, 0:2] = \n", A[0:2, 0:2] )
print("변경 후 A = \n", A)
print("\n")
# 변경 후 A[0:2, 0:2] =
#  [[0 0]
#  [0 0]]
# 변경 후 A =
#  [[ 0  0  3  4]
#  [ 0  0  7  8]
#  [ 9 10 11 12]]



# 배열의 행벡터를 출력합니다.
for row in A:
    print(row)
print("\n")
# [0 0 3 4]
# [0 0 7 8]
# [ 9 10 11 12]


# 다음처럼도 가능합니다.
for i in range(A.shape[0]):
    print(A[i,:])
print("\n")
# [0 0 3 4]
# [0 0 7 8]
# [ 9 10 11 12]


# 다음처럼도 가능합니다.
for i in range(A.shape[0]):
    print(A[i])
print("\n")
# [0 0 3 4]
# [0 0 7 8]
# [ 9 10 11 12]



# 배열의 열벡터를 출력합니다.
for column in A.T:   # A.T는 행과 열을 교환하여 얻게되는 전치 행렬(transpose matrix) 입니다.
    print(column)
print("\n")
# [0 0 9]
# [ 0  0 10]
# [ 3  7 11]
# [ 4  8 12]


# 다음처럼도 가능합니다.
for i in range(A.shape[1]):
    print(A[:,i])
print("\n")
# [0 0 9]
# [ 0  0 10]
# [ 3  7 11]
# [ 4  8 12]