### Lab 6-1 SoftMax function

softmax function : 여러개의 클래스를 예측할때 유용, n 개의 예측할 값이 있을 때 유용하다

Logistic calssifier XW = Y (주어 진 X 값에 학습할 Weight를 곱하여 값을 만들어 낸다) 허나 이것은 단순하게 score(Logit)에 불가하고 Softmax function 에 input을 하면 
Probability(확률)로 나오게 되고 모든 Score에 해당하는 확률의 &sigma; 값은 1이 된다. 

In [ ]:
#softmax function을 이용한 데이터 값의 확률 변환
#tf.matmul(X,W) + b ==> XW 
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [ ]:
#Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate =0.1).mimimize(cost)

In [2]:
import tensorflow as tf
tf.set_random_seed(777)

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
#binary classification과 다르게 여러값으로 표현 해야한다. 여러개의 class가 존재하기 때문 
#표시방법: One-Hot encoding : n개의 레이블 중에 하나의 값만 특별히 값을 부여한다.(1을 부여한다.)
y_data = [[0, 0, 1],#2
          [0, 0, 1],#2
          [0, 0, 1],#2
          [0, 1, 0],#1
          [0, 1, 0],#1
          [0, 1, 0],#1
          [1, 0, 0],#0
          [1, 0, 0]]#0
#각 input data 형식에 따라 placeholder 설정 한다.
#Y의 경우에는 레이블의 개수가 placeholder에 나타난다.
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])

nb_classes = 3#ouput 개수 
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')#bias 는 나가는 값 3개만 설정(주의)

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')

    # Testing & One-hot encoding
    # argmax를 이용해 One-hot encoding의 결과중 가장 큰 값 hot 한 값을 출력해 준다.
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 2.5190194
200 0.64940304
400 0.5320004
600 0.44949302
800 0.37788486
1000 0.30788743
1200 0.24303676
1400 0.2194125
1600 0.20043297
1800 0.18433756
2000 0.17052929
--------------
[[3.8057044e-02 9.6193278e-01 1.0239968e-05]] [1]
--------------
[[0.66531366 0.3069914  0.0276949 ]] [0]
--------------
[[2.6781443e-08 4.4821366e-04 9.9955171e-01]] [2]
--------------
[[3.8057044e-02 9.6193278e-01 1.0239968e-05]
 [6.6531366e-01 3.0699140e-01 2.7694905e-02]
 [2.6781443e-08 4.4821366e-04 9.9955171e-01]] [1 0 2]
