## Shape Rank Axis

### Shape
<br>
shape: 배열의 형태 정보를 알려준다.

In [8]:
import tensorflow as tf
sess = tf.Session()

t = tf.constant([1,2,3,4])
tf.shape(t).eval(session=sess)

array([4], dtype=int32)

해당 배열이 몇 차원으로 이루어 졌는지 배열의 요소가 몇개인지 확인할 때 사용한다.

In [9]:
import tensorflow as tf
 
sess = tf.Session()
 
t1 = tf.constant([[[[1,2,3,4],[1,2,3,4], [1,2,3,4]],
                   [[1,2,3,4],[1,2,3,4], [1,2,3,4]]]])
tf.shape(t1).eval(session=sess)

array([1, 2, 3, 4], dtype=int32)

### Tip
shape 계산법
큰 대괄호의 갯수를 센다. 이것은 Rank를 의미하게 되고 결국 shape이 
array([?,?,?,?])라는 값이 나오게 한다.
순서가 가장 작은 요소 부터 맨 오른 쪽으로 채워 나간다
1. 배열의 가장 작은 요소의 개수: 4
2. 4개의 가장 작은 요소가 모인 배열들의 개수 3개
3. 3개의 요소가 모인 배열들: 2개
4. .. 1개
즉 대괄호의 영역에 따라 가장 작은 대괄호의 요소들의 개수를 차례대로 오른쪽 부터 채워나가면 된다.
[1,2,3,4]

### Rank
<br>
배열이 몇 차원 배열인지 알수 있다.


In [13]:
import tensorflow as tf
 
sess = tf.Session()
 
t1 = tf.constant([1,2,3]) #rank = 1
t2 = tf.constant([[1,2], [3,4]]) #rank = 2

### Axis 
축의 값, Rank-1 의 최대 값을 지닌다.-> 0부터 시작하기 때문
대괄호 기준으로 가장 바깥쪽 Axis = 0 차례대로 1 , 2, 3,,

### Matmul Vs Multiple

In [17]:
import tensorflow as tf

sess = tf.Session()
matrix1 = tf.constant([[1., 2.],[3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Metrix 1 Shpae", matrix1.shape)
print("Metrix 2 Shpae", matrix2.shape)
tf.matmul(matrix1, matrix2).eval(session = sess)

Metrix 1 Shpae (2, 2)
Metrix 2 Shpae (2, 1)


array([[ 5.],
       [11.]], dtype=float32)