## Shape Rank Axis

### Shape
<br>
shape: 배열의 형태 정보를 알려준다.

In [8]:
import tensorflow as tf
sess = tf.Session()

t = tf.constant([1,2,3,4])
tf.shape(t).eval(session=sess)

array([4], dtype=int32)

해당 배열이 몇 차원으로 이루어 졌는지 배열의 요소가 몇개인지 확인할 때 사용한다.

In [9]:
import tensorflow as tf
 
sess = tf.Session()
 
t1 = tf.constant([[[[1,2,3,4],[1,2,3,4], [1,2,3,4]],
                   [[1,2,3,4],[1,2,3,4], [1,2,3,4]]]])
tf.shape(t1).eval(session=sess)

array([1, 2, 3, 4], dtype=int32)

### Tip
shape 계산법
큰 대괄호의 갯수를 센다. 이것은 Rank를 의미하게 되고 결국 shape이 
array([?,?,?,?])라는 값이 나오게 한다.
순서가 가장 작은 요소 부터 맨 오른 쪽으로 채워 나간다
1. 배열의 가장 작은 요소의 개수: 4
2. 4개의 가장 작은 요소가 모인 배열들의 개수 3개
3. 3개의 요소가 모인 배열들: 2개
4. .. 1개
즉 대괄호의 영역에 따라 가장 작은 대괄호의 요소들의 개수를 차례대로 오른쪽 부터 채워나가면 된다.
[1,2,3,4]

### Rank
<br>
배열이 몇 차원 배열인지 알수 있다.


In [13]:
import tensorflow as tf
 
sess = tf.Session()
 
t1 = tf.constant([1,2,3]) #rank = 1
t2 = tf.constant([[1,2], [3,4]]) #rank = 2

### Axis 
축의 값, Rank-1 의 최대 값을 지닌다.-> 0부터 시작하기 때문
대괄호 기준으로 가장 바깥쪽 Axis = 0 차례대로 1 , 2, 3,,

### Matmul Vs Multiple

In [17]:
import tensorflow as tf

sess = tf.Session()
matrix1 = tf.constant([[1., 2.],[3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Metrix 1 Shpae", matrix1.shape)
print("Metrix 2 Shpae", matrix2.shape)
tf.matmul(matrix1, matrix2).eval(session = sess)
#matmul의 조건: (n,s) x (n,k)

Metrix 1 Shpae (2, 2)
Metrix 2 Shpae (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

### Broadcasting 
shape이 달라도 배열 연산을 해 준다.
최대한 사용을 주의해야 한다 . 잘못 사용하면 예상하지 못한 값을 가져올 수 이기 때문에 주의

In [1]:
import tensorflow as tf

sess = tf.Session()
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.) # transform => ([[3., 3.]])
(matrix1+matrix2).eval(session = sess)

array([[4., 5.]], dtype=float32)

### Reduce operation
행렬에서 여러 값이 있을 때 줄여주는 역할 , axsis(축) 에 따라서 연산을 하여 값을 반환 한다.

In [12]:
import tensorflow as tf

sess = tf.Session()

tf.reduce_mean([1,2], axis = 0).eval(session = sess)
tf.reduce_mean([[1., 2.],[3., 4.]], axis = 0).eval(session = sess) #0축 즉 1, 3  &  2 , 4 평균을 내어 준다
tf.reduce_mean([[1., 2.],[3., 4.]], axis = 1).eval(session = sess) # 1 ,2 & 3,4 평균을 내어 준다.
tf.reduce_mean([[1., 2.],[3., 4.]]).eval(session = sess) #축 값이 없으면 모든 행열 원소들의 평균을 내어준다.
#sum 도 마찬가지

2.5

### Argmax
행렬의 원소중에서 축에 따라 가장 큰 값의 위치를 반환 해준다.

In [13]:
import tensorflow as tf

sess = tf.Session()
x = [[0, 1 , 2], [2, 1, 0]]

tf.argmax(x,axis = 0).eval(session = sess) #축이 0이다 . 즉 0, 2(1) , 1(0), 1 , 2(0), 1 

array([1, 0, 0])

In [15]:
tf.argmax(x,axis = 1).eval(session = sess)


array([2, 0])

In [16]:
tf.argmax(x,axis = -1).eval(session = sess)

array([2, 0])

### Reshape
tensor의 shape를 변경할 때 사용, 보통 가장 안쪽은 그대로 가져오고 바깥쪽을 Reshape 을 하게 된다.
#### shape에 -1 값을 넣게 되면 변경에 맞춰서 값이 들어가게 된다.

In [17]:
import tensorflow as tf
import numpy as np

# reshape

t = np.array([[[0, 1, 2],
               [3, 4, 5]], 
              [[6, 7, 8],
               [9, 10, 11]]])

print(t.shape)

sess = tf.Session()
print(tf.reshape(t, shape=[-1, 3]).eval(session=sess))
print(tf.reshape(t, shape=[-1, 1, 3]).eval(session=sess))

(2, 2, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]


### Reshape 의 Squeeze & Expand

In [19]:
tf.squeeze([[0], [1], [2]]).eval(session=sess)

array([0, 1, 2], dtype=int32)

In [20]:
tf.expand_dims([0,1,2], 1).eval(session = sess)

array([[0],
       [1],
       [2]], dtype=int32)

### One hot encoding
주어진 데이터를 0 , 1값으로 바꾸어 주는것 depth에 따라서 Rank가 생성 된다.

In [21]:
import tensorflow as tf
import numpy as np

tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=tf.Session())

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

==> 결과는 원래 데이터의 Shape +1 이기ㄷ 때문에 Reshape이 필요하다.

### Casting
dtype으로 변경 , True , False 를 0 , 1 로 바꿔준다. (one hot encoding)

In [22]:
import tensorflow as tf
import numpy as np

print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=tf.Session()))

print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval(session=tf.Session()))

[1 2 3 4]
[1 0 1 0]


### Stack

In [23]:
import tensorflow as tf
import numpy as np

x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval(session=tf.Session())

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

### Ones and Zeors like
주어진 shape 에 0 또는 1을 채운 행렬로 만들어준다.

In [24]:
import tensorflow as tf
import numpy as np

x = [[0, 1, 2],
     [2, 1, 0]]

print(tf.ones_like(x).eval(session=tf.Session())) # 1로 채운
print(tf.zeros_like(x).eval(session=tf.Session())) # 0으로 채운

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


### Zips 
복수개의 tensor를 한번에 추출 할 때 사용

In [25]:
import tensorflow as tf
import numpy as np

for x, y in zip([1, 2, 3], [4, 5, 6]): # x와 y에 담아서 처리
  print(x, y)

1 4
2 5
3 6
